version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: umechan-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - '.env'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - './data/db:/var/lib/mysql'
  api:
    build:
      dockerfile: images/Dockerfile.api
      context: .
    container_name: umechan-api
    restart: always
    depends_on:
      - db
    env_file:
      - '.env'
    environment:
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - ADMINISTATOR_KEY=${ADMINISTRATOR_KEY}
      - DEFAULT_NAME=${DEFAULT_NAME}
      - PHINX_HOSTNAME=${MYSQL_HOSTNAME}
      - PHINX_DATABASE=${MYSQL_DATABASE}
      - PHINX_USER=${MYSQL_USERNAME}
      - PHINX_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - './logs:/var/log'
  filestore:
    build:
      dockerfile: images/Dockerfile.filestore
      context: .
    container_name: umechan-filestore
    restart: always
    environment:
      - STATIC_URL=${STATIC_URL}
    volumes:
      - './data/files:/var/www/html/files'
      - './logs:/var/log'
  nginx:
    build:
      dockerfile: images/Dockerfile.frontend
      context: .
      args:
        - API_URL=${API_URL}
        - FILESTORE_URL=${FILESTORE_URL}
    env_file:
      - '.env'
    container_name: umechan-frontend
    restart: always
    depends_on:
      - api
    volumes:
      - './data/files:/var/www/html/files'
      - './logs:/var/log/nginx'
    ports:
      - '80:80'
  promtail:
    container_name: umechan-promtail
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - './logs:/var/log:ro'
    restart: always
  loki:
    container_name: umechan-loki
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
  grafana:
    container_name: umechan-grafana
    image: grafana/grafana:latest
    user: '$UID:$GID'
    ports:
      - "3000:3000"
    volumes:
      - "./data/grafana:/var/lib/grafana"
    restart: always
