services:
  db:
    image: mysql:8.3.0
    container_name: umechan-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - '.env'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - './data/db:/var/lib/mysql'
  api:
    build:
      dockerfile: images/Dockerfile.api
      context: .
    container_name: umechan-api
    restart: always
    depends_on:
      - db
    env_file:
      - '.env'
    environment:
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PHINX_HOSTNAME=${MYSQL_HOSTNAME}
      - PHINX_DATABASE=${MYSQL_DATABASE}
      - PHINX_USER=${MYSQL_USERNAME}
      - PHINX_PASSWORD=${MYSQL_PASSWORD}
      - ADMINISTATOR_KEY=${ADMINISTRATOR_KEY}
      - DEFAULT_NAME=${DEFAULT_NAME}
      - RADIO_CHAN_THREAD_ID=${RADIO_CHAN_THREAD_ID}
    volumes:
      - './logs:/var/log'
  filestore:
    build:
      dockerfile: images/Dockerfile.filestore
      context: .
    container_name: umechan-filestore
    restart: always
    environment:
      - STATIC_URL=${STATIC_URL}
      - ADMINISTRATOR_KEY=${ADMINISTRATOR_KEY}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - './data/files:/var/www/html/files'
      - './logs:/var/log'
  radio-db-importer:
    build:
      dockerfile: images/Dockerfile.radio-db-importer
      context: .
      args:
        - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USERNAME=${MYSQL_USERNAME}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    container_name: umechan-radio-db-importer
    restart: 'no'
    depends_on:
      - db
    env_file:
      - '.env'
    environment:
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - '$DIR_OF_CONVERTIBLE_FILES_PATH:/var/lib/convert:rw'
      - '$DIR_OF_TAGME_FILES_PATH:/var/lib/tagme:rw'
      - '$MUSIC_DIR_PATH:/var/lib/music:rw'
      - './logs/:/db-importer/logs:rw'
  radio-scheduler:
    build:
      dockerfile: images/Dockerfile.radio-scheduler
      context: .
      args:
        - MPD_HOSTNAME=${MPD_HOSTNAME}
        - MPD_PORT=${MPD_PORT}
        - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USERNAME=${MYSQL_USERNAME}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    container_name: umechan-radio-scheduler
    restart: always
    env_file:
      - '.env'
    volumes:
      - './logs/:/scheduler/logs'
  radio-metrics:
    build:
      dockerfile: images/Dockerfile.radio-metrics
      context: .
      args:
        - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USERNAME=${MYSQL_USERNAME}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - RADIO_API_URL=${RADIO_API_URL}
        - RADIO_CHAN_API_URL=${DOMAIN}
        - RADIO_CHAN_THREAD_ID=${RADIO_CHAN_THREAD_ID}
        - RADIO_CHAN_POSTER_KEY=${RADIO_CHAN_POSTER_KEY}
        - RADIO_DISCORD_HOOK_URL=${RADIO_DISCORD_HOOK_URL}
        - RADIO_LOG_LEVEL=${RADIO_LOG_LEVEL}
        - MPD_HOSTNAME=${MPD_HOSTNAME}
        - MPD_PORT=${MPD_PORT}
        - MPD_DATABASE_PATH=${MPD_DATABASE_PATH}
    container_name: umechan-radio-metrics
    restart: always
    depends_on:
      - db
    env_file:
      - '.env'
    environment:
      - PHINX_HOSTNAME=${MYSQL_HOSTNAME}
      - PHINX_DATABASE=${MYSQL_DATABASE}
      - PHINX_USER=${MYSQL_USERNAME}
      - PHINX_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - './logs:/usr/local/share/metrics/logs'
      - '/home/ridouchire/Music:/var/lib/music'
  nginx:
    build:
      dockerfile: images/Dockerfile.frontend
      context: .
      args:
        - API_URL=${API_URL}
        - FILESTORE_URL=${FILESTORE_URL}
        - ICECAST_URL=${ICECAST_URL}
        - BASE_URL=${BASE_URL}
    env_file:
      - '.env'
    container_name: umechan-frontend
    restart: always
    depends_on:
      - api
    volumes:
      - './data/files:/var/www/html/files'
      - './logs:/var/log/nginx'
    ports:
      - '8000:80'
  promtail:
    container_name: umechan-promtail
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - './logs:/var/log:ro'
    restart: always
  loki:
    container_name: umechan-loki
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
  grafana:
    container_name: umechan-grafana
    image: grafana/grafana:latest
    user: '$UID:$GID'
    ports:
      - "3000:3000"
    volumes:
      - "./data/grafana:/var/lib/grafana"
    restart: always
  memcached:
    container_name: umechan-memcached
    image: memcached
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
