FROM library/php:8.1-cli
WORKDIR /scheduler

RUN apt update -yyq && apt install -yyq zip libzip-dev
RUN docker-php-ext-install zip
RUN docker-php-ext-install sockets

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/usr/local/bin/ --filename composer; rm composer-setup.php

COPY radio-scheduler .
RUN composer install

ARG MPD_HOSTNAME
ARG MPD_PORT
ENV MPD_HOSTNAME $MPD_HOSTNAME
ENV MPD_PORT $MPD_PORT

CMD php ./index.php
